FROM python:3.7

WORKDIR /app

# Copy requirement file
COPY ./containers/scheduler/requirements.txt ./

COPY ./containers/scheduler/entrypoint.sh ./

# Install all required dependencies
RUN pip install flask requests python-dotenv mongo-qas --trusted-host=pypi.python.org --trusted-host=pypi.org --trusted-host=files.pythonhosted.org --default-timeout=100 && \
    pip install -r requirements.txt --trusted-host=pypi.python.org --trusted-host=pypi.org --trusted-host=files.pythonhosted.org --default-timeout=100

COPY ./containers/scheduler/code/. .

ENV FLASK_APP="app.py"

CMD ["bash", "entrypoint.sh"]